#!/bin/sh

# Ensure folder for web root if not exists
if [ ! -d /data/code/web ] ; then
  mkdir -p /data/code/web
  chown nginx:www-data /data/code/web
fi

# Create uploads directory if not exists
if [ ! -d /data/uploads ] ; then
  mkdir -p /data/uploads
  chown nginx:www-data /data/uploads
fi

mkdir -p /data/log/nginx
mkdir -p /tmp/nginx
chown nginx /tmp/nginx