#!/usr/bin/with-contenv sh
##
# Php uses msmtp binary to send email
# This script changes /etc/msmtprc settings to change the used server
# Typically you can configure 1 postfix which can send email from all containers
##

# Replace msmtp 'from' field
if [ -n "$SMTP_FROM" ]; then
  sed -i "s/^from.*$/from $SMTP_FROM/g" /etc/msmtprc
elif [ wp core is-installed ]; then
  # If SMTP_FROM was not setupped try to ask the domain from wordpress
  $smtp_from="no-reply@$(wp option get siteurl | sed 's/https\?:\/\///')"
  sed -i "s/^from.*$/from $smtp_from/g" /etc/msmtprc
fi

# Replace msmtp 'host' field
if [ -n "$SMTP_HOST" ]; then
  sed -i "s/^host.*$/host $SMTP_HOST/g" /etc/msmtprc
fi

# Replace msmtp 'port' field
if [ -n "$SMTP_PORT" ]; then
  sed -i "s/^port.*$/port $SMTP_PORT/g" /etc/msmtprc
fi

# Replace msmtp 'tls' field, possible fields on/off
if [ -n "$SMTP_TLS" ]; then
  sed -i "s/^tls.*$/tls $SMTP_TLS/g" /etc/msmtprc
fi

# Replace msmtp 'tls' field
if [ -n "$SMTP_AUTH" ]; then
  sed -i "s/^auth.*$/auth $SMTP_TLS/g" /etc/msmtprc
fi
